set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {led1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led4[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led4[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led3[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led3[0]}]

set_property PACKAGE_PIN E2 [get_ports {led1[6]}]
set_property PACKAGE_PIN D3 [get_ports {led1[5]}]
set_property PACKAGE_PIN E1 [get_ports {led1[4]}]
set_property PACKAGE_PIN F2 [get_ports {led1[3]}]
set_property PACKAGE_PIN C3 [get_ports {led1[2]}]
set_property PACKAGE_PIN C2 [get_ports {led1[1]}]
set_property PACKAGE_PIN C1 [get_ports {led1[0]}]

set_property PACKAGE_PIN B5 [get_ports {led2[6]}]
set_property PACKAGE_PIN A5 [get_ports {led2[5]}]
set_property PACKAGE_PIN A4 [get_ports {led2[4]}]
set_property PACKAGE_PIN A3 [get_ports {led2[3]}]
set_property PACKAGE_PIN C7 [get_ports {led2[1]}]
set_property PACKAGE_PIN B6 [get_ports {led2[0]}]

set_property PACKAGE_PIN A10 [get_ports {led3[6]}]
set_property PACKAGE_PIN B10 [get_ports {led3[5]}]
set_property PACKAGE_PIN A9 [get_ports {led3[4]}]
set_property PACKAGE_PIN C8 [get_ports {led3[3]}]
set_property PACKAGE_PIN A13 [get_ports {led3[2]}]
set_property PACKAGE_PIN A12 [get_ports {led3[1]}]
set_property PACKAGE_PIN B11 [get_ports {led3[0]}]

set_property PACKAGE_PIN A15 [get_ports {led4[6]}]
set_property PACKAGE_PIN B16 [get_ports {led4[5]}]
set_property PACKAGE_PIN B15 [get_ports {led4[4]}]
set_property PACKAGE_PIN A14 [get_ports {led4[3]}]
set_property PACKAGE_PIN E15 [get_ports {led4[2]}]
set_property PACKAGE_PIN D15 [get_ports {led4[1]}]
set_property PACKAGE_PIN C16 [get_ports {led4[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports mid_dot]
set_property PACKAGE_PIN B7 [get_ports mid_dot]

set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN F5 [get_ports CLK]
create_clock -period 83.334 -name CLK [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports position_bt]
set_property IOSTANDARD LVCMOS33 [get_ports set_time]
set_property IOSTANDARD LVCMOS33 [get_ports change_bt]

set_property PACKAGE_PIN M16 [get_ports reset]
set_property PACKAGE_PIN M15 [get_ports set_time]
set_property PACKAGE_PIN N16 [get_ports position_bt]
set_property PACKAGE_PIN P16 [get_ports change_bt]

set_property PACKAGE_PIN A8 [get_ports {led2[2]}]
